import Head from 'next/head';
import Header from "./header.js";
import Services from "./services.js";
import Portfolio from "./portfolio.js";
import { useContext } from "react";
import AppContext from "../components/AppContext.js";

export default function Home() {
  const context = useContext(AppContext);

  return (
    <div className={context.darkMode ? "dark" : ""}>
      <Head>
        <title>KevinPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-stone-50 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <Header />
        <Services />
        <Portfolio />
      </main>
    </div>
  );
}
