import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiOutlineMail, AiFillLinkedin, AiFillMediumSquare, AiFillGithub, AiFillBehanceSquare } from 'react-icons/ai';
import Image from "next/image";
import profile from "../public/profile.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import tutoring from "../public/tutoring.png";
import SpeecHack from "../public/SpeecHack.jpg";
import JadiRelawan from "../public/JadiRelawan.jpg";
import Juraku from "../public/Juraku.jpg";
import KoHi from "../public/Ko-Hi.jpg";
import BerKata from "../public/BerKata.jpg";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>KevinPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-stone-50 px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">kevinportfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a 
                  className="bg-gradient-to-r from-blue-600 to-blue-700 text-white px-4 py-2 rounded-md ml-8" 
                  href={"/Kevin's Resume.pdf"}
                  target={"_blank"}
                  rel={"noopener noreferrer"}
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-blue-600 font-medium dark:text-blue-400 md:text-6xl">Kevin Jonathan</h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Software Engineer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl dark:text-gray-200 max-w-lg mx-auto">
              I am Kevin Jonathan, an ambitious mobile development engineer concentrating in iOS app development and Flutter. I am an alumni from Petra Christian University and Apple Developer Academy.
            </p>
          </div>
          <div className="text-4xl flex justify-center gap-4 py-3 text-gray-600 dark:text-gray-400">
            <a href={"mailto:kevinjonathan3010@gmail.com"} target={"_blank"}>
              <AiOutlineMail />
            </a>
            <a href={"https://www.linkedin.com/in/kevinjonathan-30/"} target={"_blank"}>
              <AiFillLinkedin />
            </a>
            <a href={"https://kevin-jonathan.medium.com/"} target={"_blank"}>
              <AiFillMediumSquare />
            </a>
            <a href={"https://github.com/KevinJonathan30"} target={"_blank"}>
              <AiFillGithub />
            </a>
            <a href={"https://www.behance.net/kevinjonathan30"} target={"_blank"}>
              <AiFillBehanceSquare />
            </a>
          </div>
          <div className="relative mx-auto rounded-full w-72 h-72 mt-20 mb-20 overflow-hidden md:h-80 md:w-80">
            <Image src={profile} layout="fill" objectFit="cover" alt="profile" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am currently open to freelance opportunities (private tutoring, web and mobile app development). I have done remote work in providing <span className="text-blue-500 dark:text-blue-400">software and UI/UX design </span> especially for <span className="text-blue-500 dark:text-blue-400">new startups </span> and helped talented people to create their dream digital products and turn their ideas into reality. I am also a freelance student tutor right now teaching mathematics, physics, chemistry, and programming related topics.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including software development, UI/UX designing and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-stone-50 dark:bg-gray-800 flex-1">
              <Image src={design} width={100} height={100} className="mx-auto" alt="design" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-300">UI/UX Design</h3>
              <p className="py-2 dark:text-gray-300">
                Creating clean UI/UX designs suited for your needs following design human interface guidelines.
              </p>
              <h4 className="py-4 text-blue-600 dark:text-blue-400">Design tools I use</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Photoshop</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Illustrator</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Adobe XD</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Figma</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-stone-50 dark:bg-gray-800 flex-1">
              <Image src={code} width={100} height={100} className="mx-auto" alt="code" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-300">Software Development</h3>
              <p className="py-2 dark:text-gray-300">
                Building softwares, ranging from website and mobile application using clean code and architecture.
              </p>
              <h4 className="py-4 text-blue-600 dark:text-blue-400">List of software topics I build</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Web Development</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Android App Development</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">iOS App Development</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 bg-stone-50 dark:bg-gray-800 flex-1">
              <Image src={tutoring} width={100} height={100} className="mx-auto" alt="tutoring" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-300">Student Tutoring</h3>
              <p className="py-2 dark:text-gray-300">
                Helping students achieve their academic goals by providing personalized tutoring services.
              </p>
              <h4 className="py-4 text-blue-600 dark:text-blue-400">Topic I teach</h4>
              <p className="text-gray-800 py-1 dark:text-gray-300">Mathematics</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Physics</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Chemistry</p>
              <p className="text-gray-800 py-1 dark:text-gray-300">Programming</p>
            </div>
          </div>
        </section>
        <section>
          <div className="mt-20">
            <h3 className="text-3xl py-1 dark:text-white">UI/UX Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Alongside being a software engineer, I also do <span className="text-blue-500 dark:text-blue-400">UI/UX Design </span> freelance for customers, especially <span className="text-blue-500 dark:text-blue-400">new startups and agencies </span> for their use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Here are the list of projects that I have worked before related to UI/UX Design.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a href={"https://www.behance.net/gallery/138798873/BerKata-Web"} target={'_blank'} >
                <Image 
                  src={BerKata} 
                  className="rounded-lg object-cover" 
                  width={'100%'} 
                  height={'100%'} 
                  layout="responsive" 
                  alt="berkata"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href={"https://www.behance.net/gallery/134936171/Ko-Hi"} target={'_blank'} >
                <Image 
                  src={KoHi} 
                  className="rounded-lg object-cover" 
                  width={'100%'} 
                  height={'100%'} 
                  layout="responsive" 
                  alt="kohi"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href={"https://www.behance.net/gallery/134151915/Juraku"} target={'_blank'} >
                <Image 
                  src={Juraku} 
                  className="rounded-lg object-cover" 
                  width={'100%'} 
                  height={'100%'} 
                  layout="responsive" 
                  alt="juraku"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href={"https://www.behance.net/gallery/134145749/JadiRelawan"} target={'_blank'} >
                <Image 
                  src={JadiRelawan} 
                  className="rounded-lg object-cover" 
                  width={'100%'} 
                  height={'100%'} 
                  layout="responsive" 
                  alt="jadirelawan"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href={"https://www.behance.net/gallery/128949225/SpeecHack"} target={'_blank'} >
                <Image 
                  src={SpeecHack} 
                  className="rounded-lg object-cover" 
                  width={'100%'} 
                  height={'100%'} 
                  layout="responsive" 
                  alt="speechack"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">

            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
